server:
  port: 8888

spring:
  pid:
    file: parking.pid
  main:
    banner-mode: off
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ENC(wkSoFeLqGeOoUkI982ITej0wFlX5a//lK2QB89cSUMXZVdnHXGY620MCpLuESbamKBKsCHMpHo46/jwMQKP3aA==)
      username: ENC(IWK1Hu6MwbryJALEUS2VTA==)
      password: ENC(yCEV1gzVA9vaUePNzrOGfv+/b4UUUXw5)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false


